<?php

namespace Database\Seeders;

use App\Models\Store;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FoodsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $foods = [
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Bánh sinh nhật',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/banh-kem-1.jpg',
                'promotion' => 0,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Bánh ngọt',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/banh-kem-ut-mo-to.jpg',
                'promotion' => 0,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Bánh mì Quốc dân',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/banh-mi-quoc-dan.jpg',
                'promotion' => 0,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Bánh mì trứng',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/banh-mi-trung.jpg',
                'promotion' => 0,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Bánh tráng kẹp Combo',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/banh-trang-kep-combo.jpg',
                'promotion' => 0,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Bánh tráng trộn',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/banh-trang-tron.jpg',
                'promotion' => 0,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Bánh bông lan',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/bong-lan.jpg',
                'promotion' => 0,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Cake nõn nà',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/cake-1.jpg',
                'promotion' => 0,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Cake Tình yêu',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/cake-2.jpg',
                'promotion' => 0,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Cháo bồ câu',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/chao-bo-cau.jpg',
                'promotion' => 0,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Cơm sườn bình dân',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/com-suon.jpg',
                'promotion' => 0,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Cơm tấm',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/com-tam-suon.jpg',
                'promotion' => 0,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Cơm trứng',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/com-trung.jpg',
                'promotion' => 0,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Cua biển',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/cua.jpg',
                'promotion' => 0,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Gà nướng nguyên con',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/ga-nuong.jpg',
                'promotion' => 0,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Đùi gà chiên giòn',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/ga-ran.jpg',
                'promotion' => 0,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Hàu tái',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/hau-tai.jpg',
                'promotion' => 0,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Lẩu thái',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/lau.jpg',
                'promotion' => 0,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Mì chả',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/mi-quang.jpg',
                'promotion' => 1,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Mì quảng',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/mi-quang-2.jpg',
                'promotion' => 1,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Trà sữa Mil VN',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/milvn.jpg',
                'promotion' => 1,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Nước ép chanh',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/nuoc-chanh.jpg',
                'promotion' => 1,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Nước rau má',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/nuoc-rau-ma.jpg',
                'promotion' => 1,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Phở',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/pho.jpg',
                'promotion' => 1,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Pizza nguyệt quế',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/pizza-1.jpg',
                'promotion' => 1,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Pizza rồng thiêng',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/pizza-2.jpg',
                'promotion' => 1,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Sinh tố bơ',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/sinh-to.jpg',
                'promotion' => 1,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Combo thịt heo kháng CoV',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/thit-heo.jpeg',
                'promotion' => 1,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Trà tắc King',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/tra-sua-king.jpg',
                'promotion' => 1,
                'food_profit' => 0,
                'food_consume' => 0,
            ],
            [
                'store_id' => Store::all()->random()->id,
                'food_name' => 'Hột vịt lộn',
                'food_active' => 1,
                'price' => rand(10, 100) * 1000,
                'food_description' => 'Món ăn tâm huyết của chúng tôi',
                'food_image' => '/images/uploads/food-avatar/trung-lon.jpg',
                'promotion' => 1,
                'food_profit' => 0,
                'food_consume' => 0,
            ],

        ];
        DB::table('foods')->insert($foods);
    }
}
